// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace PMGSupportSystem.Repositories.Models;

public partial class Exam
{
    public Guid ExamId { get; set; }

    public string FilePath { get; set; }

    public Guid? UploadBy { get; set; }

    public DateTime? UploadedAt { get; set; }

    public string Semester { get; set; }

    public string BaremFile { get; set; }

    public string Status { get; set; }
    [JsonIgnore]
    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();

    public virtual User UploadByNavigation { get; set; }
}