// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMGSupportSystem.Repositories.Models;

public partial class GradeRound
{
    public Guid Id { get; set; }

    public Guid? SubmissionId { get; set; }

    public int? RoundNumber { get; set; }

    public Guid? LecturerId { get; set; }

    public decimal? Score { get; set; }

    public string Note { get; set; }

    public DateTime? GradeAt { get; set; }

    public Guid? CoLecturerId { get; set; }

    public int? MeetingUrl { get; set; }

    public DateTime? ScheduleAt { get; set; }

    public bool? Status { get; set; }

    public virtual User CoLecturer { get; set; }

    public virtual User Lecturer { get; set; }

    public virtual Submission Submission { get; set; }
}