// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMGSupportSystem.Repositories.Models;

public partial class RegradeRequest
{
    public Guid RegradeRequestId { get; set; }

    public Guid? SubmissionId { get; set; }

    public Guid? StudentId { get; set; }

    public int? RequestRound { get; set; }

    public string Status { get; set; }

    public DateTime? RequestAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    public Guid? ExaminerId { get; set; }

    public string Reason { get; set; }

    public virtual User Examiner { get; set; }

    public virtual User Student { get; set; }

    public virtual Submission Submission { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}