// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace PMGSupportSystem.Repositories.Models;

public partial class Submission
{
    public Guid SubmissionId { get; set; }

    public Guid? ExamId { get; set; }

    public Guid? StudentId { get; set; }

    public string FilePath { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public decimal? FinalScore { get; set; }

    public decimal? AiScore { get; set; }

    public Guid? PublishedBy { get; set; }

    public string Status { get; set; }

    public virtual Exam Exam { get; set; }
    [JsonIgnore]
    public virtual ICollection<GradeRound> GradeRounds { get; set; } = new List<GradeRound>();

    public virtual User PublishedByNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<RegradeRequest> RegradeRequests { get; set; } = new List<RegradeRequest>();

    public virtual User Student { get; set; }
    [JsonIgnore]
    public virtual ICollection<SubmissionDistribution> SubmissionDistributions { get; set; } = new List<SubmissionDistribution>();
}