// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace PMGSupportSystem.Repositories.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string GoogleId { get; set; }

    public string Role { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Code { get; set; }

    public bool? Status { get; set; }
    [JsonIgnore]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
    [JsonIgnore]
    public virtual ICollection<GradeRound> GradeRoundCoLecturers { get; set; } = new List<GradeRound>();
    [JsonIgnore]
    public virtual ICollection<GradeRound> GradeRoundLecturers { get; set; } = new List<GradeRound>();
    [JsonIgnore]
    public virtual ICollection<RegradeRequest> RegradeRequestExaminers { get; set; } = new List<RegradeRequest>();
    [JsonIgnore]
    public virtual ICollection<RegradeRequest> RegradeRequestStudents { get; set; } = new List<RegradeRequest>();
    [JsonIgnore]
    public virtual ICollection<RegradeRequest> RegradeRequestUpdatedByNavigations { get; set; } = new List<RegradeRequest>();
    [JsonIgnore]
    public virtual ICollection<SubmissionDistribution> SubmissionDistributions { get; set; } = new List<SubmissionDistribution>();
    [JsonIgnore]
    public virtual ICollection<Submission> SubmissionPublishedByNavigations { get; set; } = new List<Submission>();
    [JsonIgnore]
    public virtual ICollection<Submission> SubmissionStudents { get; set; } = new List<Submission>();
}