// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMGSupportSystem.Repositories.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string GoogleId { get; set; }

    public string Role { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Code { get; set; }

    public bool? Status { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    public virtual ICollection<GradeRound> GradeRoundCoLecturers { get; set; } = new List<GradeRound>();

    public virtual ICollection<GradeRound> GradeRoundLecturers { get; set; } = new List<GradeRound>();

    public virtual ICollection<RegradeRequest> RegradeRequestExaminers { get; set; } = new List<RegradeRequest>();

    public virtual ICollection<RegradeRequest> RegradeRequestStudents { get; set; } = new List<RegradeRequest>();

    public virtual ICollection<RegradeRequest> RegradeRequestUpdatedByNavigations { get; set; } = new List<RegradeRequest>();

    public virtual ICollection<SubmissionDistribution> SubmissionDistributions { get; set; } = new List<SubmissionDistribution>();

    public virtual ICollection<Submission> SubmissionPublishedByNavigations { get; set; } = new List<Submission>();

    public virtual ICollection<Submission> SubmissionStudents { get; set; } = new List<Submission>();
}